### ISSUE TITLE
Using namespace std in an header file

### ISSUE THREAD

**Issue by voichek** [refresh-bio/KMC#117]
Hi,

I am using the KMC API in my code. I have noticed that "kmer_defs.h" file add the std namespace.
To [my knowledge](https://stackoverflow.com/questions/5849457/using-namespace-in-c-headers) adding namespace in header files is not a common practice as it effects all the cpp/h files including it.

I was wondering if you could please remove it from the code, so programs using it won't be affected.

Best wishes,
Yoav Voichek

**Comment by marekkokot** [comment]
Hi,

You are absolutelly right, using namespace is a bad practice. Thanks for reporting that, it was fiexed with last commit (at least in KMC API, in KMC code we still have some using namespace in header files, maybe at some point we will fix that, but for now as we need to keep implementation in header files because of templates we will keep it the way it is, furthermore for the end user it is probably not so important, but I hope we will find a time to fix it also in KMC at some point).

Thanks again for reporting that and for using KMC.
Best,
Marek

**Comment by voichek** [comment]
Thank you for the quick response!
