### ISSUE TITLE
v2.3 errors on OSX 10.11.5

### ISSUE THREAD

**Issue by martinghunt** [refresh-bio/KMC#12]
There appears to be issues with OSX 10.11.5. As an example, the precompiled version 2.3 on OSX 10.11.5 fails on this input file:

https://www.dropbox.com/s/dipykcat21aepi8/reads.fa

using the command:

    kmc -fa  -k60 -sf1 -ci10 -cs100000000 -cx100000000 reads.fa foo .

gives the error "Error: Cannot open temporary file ... ".

But it works fine on OSX 10.8.5. (See also sanger-pathogens/iva/issues/63, looks like the homebrew version and compiling from source also fails).

**Comment by marekkokot** [comment]
Thank you for reporting that bug, unfortunately
I can't reproduce it now, because of no access to OSX, but i have a question. 
Do you set the number of simultaneously open files:

    ulimit -n 2048

it is important on mac, because by default this number is not sufficient for KMC (maybe it differs between OSX versions - I don't know). If it is set I will try to check this test case as soon as possible, so let me know.

By the way -sf has no effect without setting -sp, -so -sr (all must be set to has any effect). To set total number of threads -t should be used, and KMC will split it based on input conditions. By default it is total number of hardware threads (returned by hardware_concurrency)

**Comment by satta** [comment]
Indeed this seems to have helped. Comparing the output with low and high ulimit values:
```
[satta@tortuga:iva/tmp.common_kmers.r3gz2avi] $ ulimit -n 200                                  [master] [0]
[satta@tortuga:iva/tmp.common_kmers.r3gz2avi] $ kmc -fa  -k60 -sf1 -ci10 -cs100000000 -cx100000000 reads.fa foo .
*
Error: Cannot open temporary file ./kmc_00197.bin
[satta@tortuga:iva/tmp.common_kmers.r3gz2avi] $ ulimit -n 2048                                 [master] [1]
[satta@tortuga:iva/tmp.common_kmers.r3gz2avi] $ kmc -fa  -k60 -sf1 -ci10 -cs100000000 -cx100000000 reads.fa foo .
*
*
********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
1st stage: 0.054172s
2nd stage: 0.067197s
Total    : 0.121369s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :           18
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :          591
   No. of unique counted k-mers       :          573
   Total no. of k-mers                :        17204
   Total no. of reads                 :         1012
   Total no. of super-k-mers          :         1685
```

**Comment by martinghunt** [comment]
Thanks. I get the same behaviour on OSX 10.8.5. Works with -ulimit -n 2000, but not with -n 200.
