### ISSUE TITLE
(k,x)-mers explanation

### ISSUE THREAD

**Issue by antonioaltamura** [refresh-bio/KMC#14]
Hi, I'm not sure I understand how you split a super k-mer in (k,x)-mers (I guess x=1 is too simple and not enough explanatory) and why the subset are non-overlapping.
Could you kindly provide a pratical example with the real `x` value you use in the program? (it is 3?)

Best regards

**Comment by marekkokot** [comment]
Hi,

The subsets are overlapping, more precisely some of them are overlapping. In the example presented in the paper http://bioinformatics.oxfordjournals.org/content/31/10/1569.full.pdf+html
R1 overlapps RA.

You are right that we use 3 in our program. I may try to prepare some example for this value but its interpretation will be way more complicated because the number of subarrays to scan for x=3 is 112.

Could you please specify what exactly is not clear to you in the example presented in the paper. If everything is clear than can you please send me an example super k-mer and I will show you how it is splitted into (k,x)-mers.

Best regards

**Comment by antonioaltamura** [comment]
Maybe I can provide the example and you could confirm the correctness (obviously I want to avoid to waste your time for this), but basically the question is how you can perform a parallel extraction of kmers and count them if the subsets are overlapping?

If I extract the kmers from a (k-3)mer, the same kmers would be into the (k-2)mers too (if the (k-2)mers belongs to the same branch of the (k-3)mer).

> Therefore, we conceptually split the array of (k,1)-mers into five
non-overlapping....

maybe this statement confuses me.

**Comment by marekkokot** [comment]
They overlap because a single record in a sorted k,x-mer array may belong to to many arrays of k-mers, but conceptually all arrays of k-mers may be interpreted as non-overlaping. 

It may be still confusing...

Each conceptual subarray of k-mers in sorted k,x-mer's array is described by a triple (start_pos, end_pos, shift). Every subarray contains sorted k-mers. In the example presented in the paper those arrays are:
R1: start_pos = 0, end_pos = 2, shift = 0
R2: start_pos=2, end_pos=7,shift=0
Ra: start_pos=2, end_pos=4,shift=1
Rc: start_pos=4,end_pos=5,shift=1,
Rg: start_pos=5,end_pos=7,shift=1

We have a number of sorted arrays of k-mers. We may iterate through those arrays taking minimal k-mer at each step, so as a result we have complete list of sorted k-mers.

I hope it will help.

**Comment by antonioaltamura** [comment]
Sorry I tried to apply your explanation to the Fig.2 of the paper but I still very confused.
If possible, a minimal example of few initial steps of the process of counting with x=3 could be very helpful. 
thanks

**Comment by marekkokot** [comment]
Hi,
I missed your comment, now when I am looking for something in old issues I noticed it.
Probably two years later you are not interested in anymore, but if you do, please reopen this issue.
