### ISSUE TITLE
command line syntax issue

### ISSUE THREAD

**Issue by dcopetti** [refresh-bio/KMC#173]
Hello,
I am trying to dump (and maybe sort) the set of k-mers in the frequency range of 12-30 (both included) but I am getting stuck at the composition of the command, I guess.
This is what I do and what I get:
```
$ kmc_tools -t20 transform Sikem_HiFi_ec_21mers dump -ci12 -cx30 -s Sikem_HiFi_ec_21mers.kmc_het12-30
Error: unknown operation parameter: -ci12
```
I also tried repeating the `dump` operation
`$ kmc_tools -t20 transform Sikem_HiFi_ec_21mers dump out12 -ci12 dump out1230 -cx30 dump sorted -s`
but it does not work
Can you help me figure out where the error is? Looking at he kmc_tools documentation it is not clear what goes where.
Thanks!
Dario

**Comment by marekkokot** [comment]
Hello,

I need to write better documentation and maybe add more examples.
In your case it should be probably:
```
$ kmc_tools -t20 transform Sikem_HiFi_ec_21mers -ci12 -cx30 dump -s Sikem_HiFi_ec_21mers.kmc_het12-30
```
or (equivalent but may work slower):
```
$ kmc_tools -t20 transform Sikem_HiFi_ec_21mers dump -s Sikem_HiFi_ec_21mers.kmc_het12-30 -ci12 -cx30
```
Let me know if it works.
The philosophy is that there are parameters related to concrete operation as well as to KMC databases.
ci, cx are parameters for KMC databases so they should follow the KMC database path.
Now, the first version is better because it will filter k-mers before sorting, so there are fewer (possibly much fewer) k-mers to sort.

Thanks for using KMC.

**Comment by dcopetti** [comment]
yep, the first command works
and with your explanation it is clearer now, thanks!
