### ISSUE TITLE
Use an existing database for further counting

### ISSUE THREAD

**Issue by JulianDicken** [refresh-bio/KMC#243]
Hi,
I have multiple fasta files and need both the kmer counts of each individual file as well as the "global" count. I want to avoid counting twice, so is there a way to "resume" counting with an existing kmer DB?

**Comment by marekkokot** [comment]
Not a way to resume, but part of the kmc package is the `kmc_tools` program (documentation: https://github.com/refresh-bio/KMC/blob/master/kmc_tools.pdf). It allows to perform set operations on KMC output files. So you can count per each fasta with kmc and then combine the results using union (since you will have many KMC databases you will probably want to use `complex` operation because `union` works only on two, with `complex` you may define complex expressions). If the number of files is very large consider splitting the complex operation to many, because I'm not sure how would it behave for example for thousands of input databases. In the KMC 3 paper we showed what kmc_tools is and how to use it: https://academic.oup.com/bioinformatics/article/33/17/2759/3796399

I think maybe we were doing something similar to what you want; we had a set of samples (bacteria, as far as I remember) and wanted to detect strain-specific k-mers. In the supplementary material there are scripts so if needed you may use them as reference.
Let me know if it helps.

**Comment by JulianDicken** [comment]
I'll check that out thanks! Do you think union performance will be better than simply counting a concatenation of all files?

**Comment by marekkokot** [comment]
Hmm, it is a little more complex, and it's hard to say.
In general, if you only want the database of all samples, running KMC with all the files provided as input (you don't need to concatenate them yourself!) running KMC may be actually faster due to some additional work kmc_tools must do.
If, however, you would like to perform further operations, like for example removing some k-mers from that database of all samples based on some other database(s) it may be most performant to do as follows:
1. count each sample a_i as a kmc database d_i
2. sort each kmc database d_i with `kmc_tools` transform sort operation into d_sorted_i
3. combine all sorted into global database d_sorted_global using complex operation (with union operator `+` in file defining complex operation) of all d_sorted_i

Using d_sorted_global and d_sorted_i for some different computations with `kmc_tools` should be quite performant.
You may just try some experiments to find the best solution for your case (it's hard to advise more without knowing more details of your use case).

**Comment by JulianDicken** [comment]
Okay thank you for the quick response! Unfortunately I don't think I can share more details here -- but your help is appreciated :) 
In case it turns out to be necessary, would it be possible to modify kmc so that it can take an input database or is that fundamentally impossible? If possible, would this be a welcome PR?

**Comment by marekkokot** [comment]
At the current stage of the code, this functionality would be really hard to add (and keep things efficient, I think).
Also I'm not really sure how would you like to make it work, for example you build d_1 from s_1, and then what? d_2 from s_2 and d_1? What would be the result, all the k-mers from s_1 and s_2 I guess, but this way you don't have k-mers from s_2 alone - is that what you want?
I would really start with the approaches proposed above, and if they turn out to not be efficient enough, consider other options.

**Comment by JulianDicken** [comment]
```
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A12-H4/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A7-B11-F5/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A7-D5/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A7-E12-D6/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A8-D10-F6/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-A8-F10-D4/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-B11-E4/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-B7-A10-F4/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-B7-B11-G6/kmc" "union" "temp/union/kmc"
"kmc_tools" "simple" "temp/union/kmc" "temp/A1-B7-C10-H4/kmc" "union" "temp/union/kmc"
Error: KMC union failed: **
Stage 1: 100%
Stage 2: 100%

❯ kmc_tools info temp/A1-B7-C10-H4/kmc
k                 :  31
total k-mers      :  165074
cutoff max        :  1000000000
cutoff min        :  2
counter size      :  4 bytes
mode              :  occurrence counters
both strands      :  yes
database format   :  KMC2.x
signature length  :  9
number of bins    :  512
lut_prefix_len    :  3
```

I got this running. its running kmc_tools with the arguments simple, a union kmc database path and the kmc database to add to the union database, and then writes this back into union/kmc. As you can see this works for the first few databases and then just fails without indication of what went wrong. There doesn't seem to be anything wrong with the underlying fastq file as the kmc database and dump work just fine. 
I cannot use the complex operation to do this all in one step, the files are in a zip archive and I pull them out one at a time for analysis -- I can at best do this step in bulk but that is besides the point. Am I missing something ?

**Comment by marekkokot** [comment]
Oh, you cannot write to the exact location you are reading from. I need to add a check for this and generate an error message. 
You may use what you figured out, write to some other location, and then just `mv` after the operation.

BTW, does it mean you only know the single fasta file you want to process at a time? I'm asking because if you know more of them, it would be more beneficial to lower the number of kmc runs by running it on a couple of samples at once (or using complex op on a couple of kmc databases, depending on your needs).
